<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>Resources\AppIcon.ico</ApplicationIcon>
    <AssemblyName>RockefellerFiction</AssemblyName>
    <RootNamespace>RockefellerFiction</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Resource Include="Resources\AppIcon.png" />
    <Resource Include="Resources\AppIcon.ico" />
    <Resource Include="Resources\Help.png" />
  </ItemGroup>
</Project>